from django.conf.urls import patterns, include, url
from apps.core.shortcuts import direct_to_template

urlpatterns = patterns(
    'apps.catalog.views',
    url(r'^$', 'index', name='index'),
    url(r'services/$', 'service_list', name='service-list'),
    url(r'services/specials/(?:(?P<service_name>\w+)/)?$', 'all_specials',
        name='all-specials'),
    url(r'services/(?P<service_pk>\d+)/$', 'catalog_list',
        name='catalog-list'),
    url(r'services/(?P<codename>[\w\d\.\-\_]+)/$', 'catalog_list',
        name='catalog-list'),
    url(r'services/(?P<codename>[\w\d\.\-\_]+)/specials/$',
        'catalog_list', {'is_special': True},
        name='catalog-list-specials'),
    url(r'service/(?P<pk>\d+)/$', 'service_page', name='service-page'),
    url(r'service/(?P<pk>\d+)/category/(?P<category_pk>\d+)/$',  # (?P<title>[\w\d\s\-\_\.\ ,]+)/$',
        'service_page', name='service-page'),
    url(r'service/(?P<pk>\d+)/rating/$',
        'service_rating', name='service-rating'),
    url(r'service/(?P<pk>\d+)/about/$',
        'service_about', name='service-about'),
    url(r'service/(?P<pk>\d+)/specials/$',
        'service_specials', name='service-specials'),
    url(r'service/specials/(?P<pk>\d+)/$',
        'service_partner_specials',
        name='service-partner-specials'),
    url(r'service/specials/(?P<pk>\d+)/edit/$',
        'special_add', name='special-edit'),
    url(r'service/specials/(?P<pk>\d+)/delete/$',
        'special_del', name='special-del'),
    url(r'service/specials/add/$',
        'special_add', name='special-add'),
    url(r'service/orders/notconfirmed/$', 'service_orders_nc',
        name='service-orders'),
    url(r'service/orders/$', 'service_orders',
        name='service-orders-confirmed'),
    url(r'service/orders/(?P<pk>\d+)/info/$', 'service_order_info',
        name='service-order-info'),
    url(r'service/orders/(?P<pk>\d+)/update/$', 'service_order_update',
        name='service-order-update'),
    url(r'containers/$', 'container_list', name='container-list'),
    url(r'containers/(?P<pk>\d+)/$', 'container', name='container'),
    url(r'containers/add/$', 'container_add', name='container-add'),
    url(r'containers/(?P<pk>\d+)/add/$', 'container_add', name='container-add'),
    url(r'containers/(?P<pk>\d+)/edit/$', 'container_edit', name='container-edit'),
    url(r'containers/(?P<pk>\d+)/delete/$', 'container_delete', name='container-delete'),
    url(r'containers/items/add/$', 'item_add', name='item-add'),
    url(r'containers/items/(?P<pk>\d+)/add/$', 'item_add', name='item-add'),
    url(r'containers/items/(?P<pk>\d+)/edit/$', 'item_edit', name='item-edit'),
    url(r'containers/items/(?P<pk>\d+)/delete/$', 'item_delete', name='item-delete'),
    url(r'containers/items/(?P<pk>\d+)/special/off/$',
        'item_special_off',
        name='special-off'),
    url(r'containers/items/(?P<pk>\d+)/description/popup/$',
        'item_description_popup', name='item-description-popup'),
    url(r'containers/addons/add/$', 'addon_add', name='addon-add'),
    url(r'containers/(?P<pk>\d+)/addons/add/$', 'addon_add', name='addon-add'),
    url(r'containers/(?P<pk>\d+)/addons/edit/$', 'addon_edit', name='addon-edit'),
    url(r'containers/(?P<pk>\d+)/addons/list/$', 'addon_list', name='addon-list'),
    url(r'containers/addons/(?P<pk>\d+)/delete/$', 'addon_delete', name='addon-delete'),
    url(r'containers/csv/import/$', 'csv_import', name='csv-import'),
    url(r'cart/$', 'cart', name='cart'),
    url(r'cart/item/add/$', 'cart_item_add', name='cart-item-add'),
    url(r'cart/item/add/(?P<item_pk>\d+)/$', 'add_item_to_cart', name='cart-item-add'),
    url(r'cart/item/add/(?P<item_pk>\d+)/(?P<quantity>\d+)/$',
        'add_item_to_cart', name='cart-item-add'),
    url(r'cart/item/checkout/(?P<item_pk>\d+)/(?P<quantity>\d+)/$',
        'add_item_to_cart',
        {'checkout': True},
        name='cart-item-set'),
    url(r'cart/item/remove/(?P<item_pk>\d+)/$',
        'remove_item_from_cart', name='cart-item-remove'),
    # url(r'cart/item/(?P<item_pk>\d+)/addon/add/(?P<addon_pk>\d+)/$', 'add_addon_to_cart', name='cart-addon-add'),
    # url(r'cart/item/(?P<item_pk>\d+)/addon/add/(?P<addon_pk>\d+)/(?P<quantity>\d+)/$',
    #    'add_addon_to_cart', name='cart-addon-add'),

    url(r'cart//addon/add/(?P<addon_pk>\d+)/(?P<quantity>\d+)/$',
        'add_addon_to_cart', name='cart-addon-add'),
    url(r'cart/addon/checkout/(?P<addon_pk>\d+)/(?P<quantity>\d+)/$',
        'add_addon_to_cart',
        {'checkout': True},
        name='cart-addon-checkout'),
    url(r'cart/addons/add/$', 'add_addons_to_cart',
        name='add-addons-to-cart'),
    url(r'cart/addon/remove/(?P<addon_pk>\d+)/$',
        'remove_addon_from_cart', name='cart-addon-remove'),
    url(r'cart/order/$', 'order', name='order'),
    url(r'cart/order/popup/$', 'order_popup', name='cart-order-popup'),
    url(r'cart/order/success/$', direct_to_template,
        {'template': 'catalog/order_success.html'},
        name='order-success'),
    url(r'cart/cleanse/$', 'cart_cleanse', name='cart-cleanse'),
    url(r'orders/$', 'orders', name='orders'),
    url(r'orders/(?P<pk>\d+)/repeat/$', 'order_repeat',
        name='order-repeat'),
    url(r'orders/partner/$', 'orders_partner', name='orders-partner'),
    url(r'orders/partner/csv/$', 'orders_partner_csv',
        name='orders-partner-csv'),
    url(r'orders/(?P<sid>[\w\d]+)/vote/$',
        'order_vote', name='order-vote'),
    url(r'orders/vote/successfull/$', direct_to_template,
        {'template': 'catalog/order_vote_success.html'},
        name='order-vote-success'),
    url(r'orders/payment/income/$', 'order_payment_notification',
        name='order-payment-notification'),
    url(r'orders/payment/success/$', direct_to_template,
        {'template': 'catalog/payment_success.html'},
        name='payment-success'),
    url(r'orders/payment/failure/$', direct_to_template,
        {'template': 'catalog/payment_failure.html'},
        name='payment-failure'),
    url(r'cart/is/empty/$', direct_to_template,
        {'template': 'catalog/empty_cart.html'},
        name='empty-cart'),
    url(r'addons/get/(?P<pk>\d+)/$', 'get_addons',
        name='addons-get'),
    url(r'orders/(?P<pk>\d+)/update_status/(?P<status>\w+)',
        'update_order_status', name='update_order_status')
)
